name: Frontend CI

on:
  push:
    branches: [ main ] # Assuming 'main' is the primary branch
  pull_request:
    branches: [ main ] # Assuming 'main' is the primary branch

jobs:
  build-and-test:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend-app # Set default working directory for all run steps

    strategy:
      matrix:
        node-version: [20.x] # Using Node.js 20.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm dependencies
          cache-dependency-path: frontend-app/package-lock.json # Path to package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Run unit and integration tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Run Cypress E2E tests
        run: npm run ci:cy
        env:
          # Optionally set CYPRESS_BASE_URL if your Cypress tests need it explicitly
          # and start-server-and-test doesn't implicitly handle it.
          # For instance, if cypress.config.ts doesn't use a relative path or
          # if tests don't adapt to the preview server's port automatically.
          # CYPRESS_BASE_URL: http://localhost:4173 # Default Vite preview port
          # However, start-server-and-test should pass the URL to Cypress if configured correctly.
          # The 'e2e' script in package.json is just 'cypress run'.
          # Cypress will use its baseUrl from cypress.config.ts unless overridden by CYPRESS_BASE_URL.
          # The ci:cy script specifies http://localhost:4173 for start-server-and-test,
          # so Cypress should target this. If cypress.config.ts baseUrl is different and not overridden,
          # tests might target the wrong URL. It's safer to explicitly set CYPRESS_BASE_URL for CI.
          CYPRESS_BASE_URL: http://localhost:4173
