name: Frontend CI

on:
  push:
    branches: [ main ] # Assuming 'main' is the primary branch
  pull_request:
    branches: [ main ] # Assuming 'main' is the primary branch

jobs:
  build-and-test:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend-app # Set default working directory for all run steps

    strategy:
      matrix:
        node-version: [20.x] # Using Node.js 20.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm dependencies
          cache-dependency-path: frontend-app/package-lock.json # Path to package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Run tests
        # This step will likely fail or do nothing if 'npm test' is not configured.
        # This is acceptable for now as we are setting up the CI structure.
        # To prevent failure if 'test' script is missing, can use:
        # run: npm test || true
        # Or define a placeholder test script in package.json: "test": "echo \"No tests specified\" && exit 0"
        run: npm test --if-present # Runs only if 'test' script exists

      - name: Build application
        run: npm run build
