"""create_profile_historical_stats_table

Revision ID: 97e98559e8b5
Revises: e20d63401b85
Create Date: 2025-05-25 14:29:06.561215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e98559e8b5'
down_revision: Union[str, None] = 'e20d63401b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_historical_stats',
        sa.Column('profile_id', sa.String(), nullable=False),
        sa.Column('success_rate_7d', sa.Float(), nullable=True),
        sa.Column('success_rate_30d', sa.Float(), nullable=True),
        sa.Column('success_rate_90d', sa.Float(), nullable=True),
        sa.Column('bid_frequency_7d', sa.Float(), nullable=True),
        sa.Column('bid_frequency_30d', sa.Float(), nullable=True),
        sa.Column('bid_frequency_90d', sa.Float(), nullable=True),
        sa.Column('last_updated_at', sa.DateTime(), nullable=True), # Default/onupdate handled by model, not migration
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_historical_stats_profile_id_profiles'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('profile_id', name=op.f('pk_profile_historical_stats'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_historical_stats')
    # ### end Alembic commands ###
