"""Add default to profiles.id

Revision ID: cd9142b3444e
Revises: 97e98559e8b5
Create Date: 2025-05-31 13:57:45.098171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9142b3444e'
down_revision: Union[str, None] = '97e98559e8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    op.create_table('agency_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'MEMBER', name='agencyrole'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'user_id', name='uq_agency_user_membership')
    )
    op.create_index(op.f('ix_agency_members_id'), 'agency_members', ['id'], unique=False)
    op.alter_column('autobid_settings', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('autobid_settings', 'daily_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('bids', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bids', 'status')
    op.alter_column('autobid_settings', 'daily_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('autobid_settings', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_agency_members_id'), table_name='agency_members')
    op.drop_table('agency_members')
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
