"""Add title and overview to Profile model

Revision ID: dd7b0bd9fda0
Revises: 50a8efc5a065
Create Date: 2025-05-31 19:07:30.788121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7b0bd9fda0'
down_revision: Union[str, None] = '50a8efc5a065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('title', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('overview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'overview')
    op.drop_column('profiles', 'title')
    # ### end Alembic commands ###
