"""add_description_embedding_to_job_model

Revision ID: e20d63401b85
Revises: 4a005d9243b4
Create Date: 2025-05-25 14:22:48.105512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# If using ARRAY(Float) for PostgreSQL:
# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e20d63401b85'
down_revision: Union[str, None] = '4a005d9243b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description_embedding', sa.JSON(), nullable=True))
    # If using ARRAY(Float) for PostgreSQL, the line would be:
    # op.add_column('jobs', sa.Column('description_embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'description_embedding')
    # ### end Alembic commands ###
