"""add predicted_score to job

Revision ID: e20d63401b86
Revises: e20d63401b85
Create Date: 2024-03-15 10:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e20d63401b86'
down_revision: Union[str, None] = 'e20d63401b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('predicted_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'predicted_score')
    # ### end Alembic commands ###
