"""add missing fields to jobs table

Revision ID: e20d63401b87
Revises: e20d63401b86
Create Date: 2024-06-03 12:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # If using UUID or other PostgreSQL specific types not used here directly but good practice

# revision identifiers, used by Alembic.
revision: str = 'e20d63401b87'
down_revision: Union[str, None] = 'e20d63401b86' # Points to the migration that added predicted_score
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('upwork_job_id', sa.String(), nullable=True)) # Changed to nullable=True for safety on existing tables
    op.add_column('jobs', sa.Column('url', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('posted_time', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('raw_data', sa.JSON(), nullable=True))

    # Explicitly create index for upwork_job_id, and make it unique if data allows or after cleanup
    # For now, creating as non-unique index. If it must be unique and nullable=False,
    # that requires the table to be empty or data to satisfy this.
    # The model has unique=True, index=True, nullable=False.
    # This migration makes it nullable=True and non-unique index to apply safely first.
    # A separate step or manual adjustment might be needed for unique=True and nullable=False.
    op.create_index(op.f('ix_jobs_upwork_job_id'), 'jobs', ['upwork_job_id'], unique=False) # Changed unique to False for safety
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_upwork_job_id'), table_name='jobs')
    op.drop_column('jobs', 'raw_data')
    op.drop_column('jobs', 'posted_time')
    op.drop_column('jobs', 'url')
    op.drop_column('jobs', 'upwork_job_id')
    # ### end Alembic commands ###
